### ISSUE TITLE
Another suggestion

### ISSUE THREAD

**Issue by Skyexir** [foncused/ExplosionRegeneration#4]
You can add an option to ignore some blocks, this could be useful for example so that the tnt can explode again in chain (tnt cannon) 
Thanks for reading
 : )

**Comment by foncused** [comment]
Hi, this should already be available in the config.

filter - list of Material names to NOT regenerate (default FIRE)

**Comment by foncused** [comment]
If you want to not regenerate TNT for example:

```
filter:
  - "TNT"
```

**Comment by Skyexir** [comment]
This is not what I would like, this option prohibits the regeneration of tnt, but what I would like is that the explosion of tnt can ignite other tnt (like in the original minecraft game)

**Comment by foncused** [comment]
Added in version 1.3.10 of the plugin.

```
# Should TNT be exploded in a chain reaction, similar to how it would normally?
tnt-chaining:
  enabled: false
  max-fuse-ticks: 40
```
